# Generated by Django 5.0.3 on 2024-03-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghazals', '0002_discussion_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='reply_to_id',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
